# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

%package -n patterns-sailfish-device-adaptation-xqdc72
Summary: Jolla HW Adaptation xqdc72
Requires: droid-hal-pdx235
Requires: droid-hal-pdx235-img-boot
Requires: droid-hal-pdx235-kernel-dtbo
Requires: droid-config-xqdc72-sailfish
Requires: droid-config-xqdc72-pulseaudio-settings
Requires: droid-config-xqdc72-policy-settings
Requires: droid-config-xqdc72-preinit-plugin
Requires: droid-config-xqdc72-flashing
Requires: droid-config-xqdc72-bluez5
Requires: droid-hal-version-xqdc72
Requires: droid-hal-pdx235-detritus

# For mount partitions
Requires: parse-android-dynparts

# For suspend to work with enabled Wi-Fi on newer Qualcomm devices (from droid-config-sony-nagara)
Requires: sailfish-connman-plugin-suspend

# Hybris packages
Requires: libhybris-libEGL
Requires: libhybris-libGLESv2
Requires: libhybris-libwayland-egl

# Sensors
Requires: sensorfw-qt5 = 0.15.1
Requires: hybris-libsensorfw-qt5-binder >= 0.15.2

# Bluetooth
Requires: bluebinder

# Telephony
Requires: ofono-binder-plugin
Requires: dummy_netd
#Requires: ofono-vendor-qti-radio-plugin
Requires: ofono-binder-plugin-ext-qti

# Bluetooth telephony
# From ringus's work on nagara
Requires: droid-bthelper

# Vibra
Requires: ngfd-plugin-native-vibrator
Requires: libngf-qt5-qtfeedback

# Needed for /dev/touchscreen symlink
Requires: qt5-plugin-generic-evdev

Requires: pulseaudio-modules-droid = 14.2.106
Requires: pulseaudio-modules-droid-hidl

# The -dummy-af is needed for newer devices that run the main
# audiosystem-passthrough in qti mode (e.g. >=Android 9 Qualcomm),
# to fix non-responding Camera app and/or voice during a phone call:
Requires: audiosystem-passthrough-dummy-af

# for audio recording to work:
Requires: qt5-qtmultimedia-plugin-mediaservice-gstmediacapture

# These need to be per-device due to differing backends (fbdev, eglfs, hwc, ..?)
Requires: qt5-qtwayland-wayland_egl
Requires: qt5-qpa-hwcomposer-plugin
Requires: qtscenegraph-adaptation

# For hybris devices with droidmedia, see HADK pdf for more information
Requires: gstreamer1.0-droid
Obsoletes: gmp-droid

# This is needed for notification LEDs
Requires: mce-plugin-libhybris

# USB mode controller
Requires: usb-moded

# hammerhead, grouper, and maguro use this in scripts, so include for all
Requires: rfkill

# enable device lock and allow to select untrusted software
Requires: jolla-devicelock-daemon-encsfa

# Enable fingerprint reader
# TODO: I can't seem to build fake_crypt so I can't use community fpd, and I tried official fpd but I have "vendor.egistec.hardware.fingerprint@4.0::IBiometricsFingerprintRbs/default" where it wants "android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default"
#Requires: sailfish-devicelock-fpd
#Requires: sailfish-fpd

# Enable home encryption
#Requires: sailfish-device-encryption

# For GPS
Requires: geoclue-provider-hybris

# For FM radio on some QCOM devices
#Requires: qt5-qtmultimedia-plugin-mediaservice-irisradio
#Requires: jolla-mediaplayer-radio

# NFC support
# 1. binder plugin requires Android 8 or a newer base
# 2. pn54x plugin talks directly to pn54x driver
# These plugins are mutually exclusive, you need to pick one:
Requires: nfcd-binder-plugin
#Requires: nfcd-pn54x-plugin

# Splash screen
#Requires: yamuisplash

%description -n patterns-sailfish-device-adaptation-xqdc72
Pattern with packages for xqdc72 HW Adaptation

%files -n patterns-sailfish-device-adaptation-xqdc72
