adsp_loader_dlkm
apr_dlkm
aw882xx_dlkm
bolero_cdc_dlkm
bt_fm_slim
btpower
bu520x1nvx
camera
ec617_drv
focaltech_fts
haptic
leds-aw2016
machine_dlkm
mbhc_dlkm
native_dlkm
p73
pinctrl_lpi_dlkm
platform_dlkm
q6_dlkm
q6_notifier_dlkm
q6_pdr_dlkm
rdbg
rmnet_core
rmnet_ctl
rmnet_offload
rmnet_shs
rx_macro_dlkm
sec_ts_drv
snx0
snd_event_dlkm
stub_dlkm
swr_ctrl_dlkm
swr_dlkm
tx_macro_dlkm
va_macro_dlkm
wcd937x_dlkm
wcd937x_slave_dlkm
wcd938x_dlkm
wcd938x_slave_dlkm
wcd9xxx_dlkm
wcd_core_dlkm
wsa881x_analog_dlkm
wlan